# This is a basic workflow to help you get started with Actions

name: Dailyreport

# Controls when the workflow will run
on:
  push:
#   schedule:
  #Runs at 00:30 UTC every day.东八区0点，北京时间早上八点
#     - cron: '00 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.16
      # - name: 'Install dependencies'
      #   run: python -m pip install --upgrade pip
      - name: 'Install NodeJs'
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: 'Install config'
        env:
          EMAILPSW: ${{ secrets.EMAILPSW }}
          PSW: ${{ secrets.PSW }}
          RECEIVEADDRESS: ${{ secrets.RECEIVEADDRESS }}
          SENDADDRESS: ${{ secrets.SENDADDRESS }}
          USERNAME: ${{ secrets.USERNAME }}
          CONFIG: ${{ secrets.CONFIG }}
        run: echo $CONFIG > ./src/config.json
    
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        run: cd ./src&&python vpnmain.py
